version: '3'
services:
  apacheasix:
    build:
      context: .
      dockerfile: asix/dockerfile
    ports:
      - "81:80"
    volumes:
      - ./asix/src/:/var/www/html
    networks:
      - mired
#        ipv4_address: 192.168.10.3

  apachedaw:
    build:
      context: .
      dockerfile: daw/dockerfile
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - ./daw/src/:/var/www/html
    networks:
      - mired
#        ipv4_address: 192.168.10.3

networks:
  mired:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.10.0/24
#          gateway: 192.168.10.1