FROM php:7.4-apache
#RUN apt update
#RUN apt upgrade -y
RUN service apache2 restart 
RUN apt-get install -y curl
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html
RUN a2enmod ssl
