# compose.yml
version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  apache2:
    image: php:apache
    ports:
      - 82:80
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=misdatos
    ports:
      - 3307:3306
    volumes:
      - mariadb_proves:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 81:80
volumes:
  mariadb_proves: