version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 81:80
    volumes:
      - ./pagina/:/var/www/html
    networks:
      - mired
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=misdatos
    ports:
      - 3307:3306
    volumes:
      - mariadb_examen:/var/lib/mysql
    networks:
      - mired

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 83:80
    networks:
      - mired

networks:
  mired:
   driver: bridge

volumes:
  mariadb_examen:
