---

- hosts: WEBSERVERS

  tasks:

  - name: Crear pagina
    template:
      src: templates/000-default.conf.j2
      dest: /etc/apache2/sites-available/{{ servername }}.conf

  - name: Crear directory para php
    file:
      path: /var/www/html/{{ servername }}
      state: directory

  - name: Contenido pagina
    copy:
      content: "<?php echo 'HOLA ' . $_GET['nom']; ?>"
      dest: /var/www/html/hola.php

  - name: Reiniciar Apache
    service:
      name: apache2
      state: restarted

  - name: Habilitamos la pagina {{ servername }}
    shell: "a2ensite {{ servername}}.conf"